writer_task:
  description: >
    Você receberá esse resumo de um documento PGR e deverá estruturá-lo de forma clara e concisa: {results}
    É preciso que você retorne esse resumo estruturado para a equipe de analistas.
  expected_output: >
    Resumo estruturado do documento PGR recebido.
    Exemplo de estruturação:
      {
        "GHE": "01",
        "Setor": "ADMINISTRATIVO",
        "Riscos": [
            {
                "Tipo de agente": "Ergonômico",
                "Descrição do agente": "Postura Sentada Por Longos Períodos",
                "Nível de risco": "TOLERÁVEL B"
            },
            # Outros riscos...
        ]
      },
  agent: Writer

