visionanalyst_task:
  description: >
    Você receberá páginas de um documento PGR PDF, e deverá extrair as seguintes informações:
    Você precisa extrair do documento, cada grupo de risco, descrição (ou tipo) do risco (ou agente) e nível (classificação) de risco que cada GHE possui. 
    Você precisa apresentar todos os grupos de risco (ou descrição do risco), tipos de risco (ou descrição do agente), niveis de risco (ou classificação do risco) para cada tipo, vinculados a cada GHE presente no dado de ghes fornecido.
    O ou significa que os documentos podem seguir esses dois tipos de padrão, ou seja, pode ser que o documento tenha um padrão ou outro, ou ambos misturados.
    Tome cuidado com informações incompletas ou inventadas. É necessário que todos os dados sejam extraídos do documento.
    Todas as informações estarão em tabelas no documento original. Ao ser extraido pode ser que as informações estejam em formato estruturado ou não.
    O caminho para a imagem é: {image_paths_url}
  expected_output: >
    Fique SEMPRE atento ao cabeçalho de cada tabela, pois nele estará o nome do GHE e o setor ao qual ele pertence. 
    Tudo que estiver abaixo do indicador do GHE e RECONHECIMENTO DOS RISCOS OCUPACIONAIS é o que você precisa extrair e organizar.
    Exemplo de resposta com informações fictícias, altere para os dados reais:
      - *GHE 01* - *Setor*:
        - *Descrição do risco (ou descrição do agente)*:
          - *Físico*:
            - *Descrição do agente (ou risco)*: ...;
              - *Nível de risco (ou classificação do risco)*: ...;
            ...
          - *Químico*:
            - *Descrição do agente (ou risco)*: ...;
              - *Nível de risco (ou classificação do risco)*: ...;
            ...
          ...
      - *GHE 02* - *Setor*:
        ...
  agent: VisionAnalyst
