ghedetector_task:
  description: >
    Analise o pdf recebido de um docuemnto PGR e identifique todos os GHEs, Grupo Homogêneo de Exposição, presentes no documento.
    Lembrando que o GHE é um grupo de trabalhadores que possuem exposição semelhante a um agente de risco.
    Utilize a {query} para retornar a lista de GHEs encontrados.
    Cuidado com a formatação do PDF pois haverá troca de páginas no documento que causa a quebra de seções.
  expected_output: >
    Retorne TODOS os GHEs encontrados no documento. Utilize a {query} para retornar a lista de GHEs encontrados.
    Cuidado sempre para pegar todos os grupos presentes referentes a GHE, Grupo de cargos Homogêneos de Exposição.
    Caso não tenha encontrado nenhum GHE, retorne uma lista vazia.
    É necessário apenas do GHE e seu número.
    Exemplo de resposta:
    ghes = [GHE 01, GHE 02, GHE 03, GHE 04, GHE 05]
  agent: GheDetector

