agentpgrmodel_task:
  description: >
    Lembre-se de organizar os dados de forma correta de acordo com o necessário para ter uma boa visão do documento analisado. O seu foco é o {ghe}
    Você precisa apresentar todos os tipos de agente (ou descrição do risco), todos os riscos (ou descrição do agente) associados a cada tipo de agente (ou descrição do risco) e também todos os niveis de risco (ou classificação do risco) para cada risco, viculados ao {ghe}
    O ou significa que os documentos podem seguir esses dois tipos de padrão, ou seja, pode ser que o documento tenha um padrão ou outro, ou ambos misturados.
    Todas as páginas extraídas são correspondentes ao {ghe}, ou seja, tudo que estiver nas páginas correspondem ao ghe que você está analisando.
  expected_output: >
    Tome cuidado com informações incompletas ou inventadas. É necessário que todos os dados sejam extraídos do documento.
    Todas as páginas extraídas são correspondentes ao {ghe}.
    Extraia todos os tópicos encontrados nas páginas, pois tudo será correspondente ao {ghe}. Não deixe nada de fora, tudo que estiver sendo citado que se encaixe nos padrões solicitados, deve ser extraído e alocado corretamente.
    Sempre que for encontrado uma descrição de agente ou risco benzeno, deve ser alocado juntamente com Tolueno, Xileno e Etilbenzeno, pois são agentes químicos que estão sempre juntos.
    Cuidado com confusão entre riscos Acidente e Físico, como por exemplo, um risco de queda de mesmo nível é acidente e não físico.
    Se encontrado A/C-, é um risco, cuidado para não se confundir.
    Exemplo de resposta com informações fictícias, altere para os dados reais e não escreva nada além das informações extraidas, textos no final da análise não são necessários. Faça em estrutura de JSON:
      "{ghe} = [
        "(Físico ou Ergonômico ou Químico ou Acidente): [
          "Descrição do agente (ou risco)": "";
            "Nível de risco (ou classificação do risco)": "";
        ]
      ]
  agent: AgentModel